# Generated by Django 2.2.4 on 2019-08-26 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_liked',
            field=models.BooleanField(default=False),
        ),
    ]
